# Generated by Django 4.0.5 on 2022-06-14 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kithub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BagIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
                ('bagtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kithub.bagtype')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kithub.part')),
            ],
            options={
                'unique_together': {('name', 'bagtype')},
            },
        ),
        migrations.CreateModel(
            name='KitIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
                ('bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kithub.bag')),
                ('kittype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kithub.kittype')),
            ],
            options={
                'unique_together': {('name', 'kittype')},
            },
        ),
        migrations.RemoveField(
            model_name='kitcontents',
            name='bag',
        ),
        migrations.RemoveField(
            model_name='kitcontents',
            name='kit',
        ),
        migrations.DeleteModel(
            name='BagContents',
        ),
        migrations.DeleteModel(
            name='KitContents',
        ),
    ]
