# Generated by Django 4.0.5 on 2022-06-14 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kithub', '0002_bagingredient_kitingredient_remove_kitcontents_bag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagingredient',
            name='bagtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='kithub.bagtype'),
        ),
        migrations.AlterField(
            model_name='bagingredient',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needed', to='kithub.part'),
        ),
        migrations.AlterField(
            model_name='bagtype',
            name='kind',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='kitingredient',
            name='bag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needed', to='kithub.bag'),
        ),
        migrations.AlterField(
            model_name='kitingredient',
            name='kittype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='kithub.kittype'),
        ),
        migrations.AlterField(
            model_name='kittype',
            name='kind',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
