# Generated by Django 4.0.5 on 2022-06-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kithub', '0003_alter_bagingredient_bagtype_alter_bagingredient_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
