# Generated by Django 4.0.5 on 2022-06-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kithub', '0005_kitingredient_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagingredient',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kitingredient',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
