# Generated by Django 4.0.5 on 2022-06-14 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kithub', '0006_bagingredient_quantity_alter_kitingredient_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitingredient',
            name='bag',
        ),
        migrations.AddField(
            model_name='kitingredient',
            name='bagtype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='needed', to='kithub.bagtype'),
            preserve_default=False,
        ),
    ]
