---
- hosts: api_servers
  gather_facts: no
  vars:
    project_dir: ~/kithub
    nginx_templates: nginxtemplates
    api_container: kithub_api_1
  vars_files:
    - secrets.yml
  tasks:
    - name: Make sure destination dir exists
      file:
        path: "{{ project_dir }}"
        state: directory

    - name: Make sure nginx templates dir exists
      file:
        path: "{{ project_dir }}/{{ nginx_templates }}"
        state: directory

    - name: Copy nginx template file
      ansible.builtin.copy:
        src: "../{{ nginx_templates }}/default.conf.template"
        dest: "{{ project_dir }}/{{ nginx_templates }}/default.conf.template"
        follow: yes

    - name: Copy Docker Compose file
      ansible.builtin.copy:
        src: ../docker-compose.yml
        dest: "{{ project_dir }}/docker-compose.yml"
        follow: yes

    - name: Copy production .env
      ansible.builtin.copy:
        src: ../production.env
        dest: "{{ project_dir }}/.env"
        follow: yes

    - name: Log into DockerHub
      community.docker.docker_login:
        username: "{{ DOCKER_USERNAME }}"
        password: "{{ DOCKER_PASSWORD }}"

    - name: Run docker-compose
      community.docker.docker_compose:
        project_src: "{{ project_dir }}"
        state: present
        pull: yes

    - name: Collect static files Django
      community.docker.docker_container_exec:
        container: "{{ api_container }}"
        command: ./manage.py collectstatic --noinput

    - name: Run migrate on Django
      community.docker.docker_container_exec:
        container: "{{ api_container }}"
        command: ./manage.py migrate
